---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-besu-test
    image: molecule-besu-test:latest
    dockerfile: ../docker/Dockerfile.debian
    privileged: true
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
verifier:
  name: ansible
