FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies.
RUN apt update \
    && apt install -y --no-install-recommends \
       ca-certificates \
       python3 \
       systemd \
       sudo \
    && apt clean \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
  /etc/systemd/system/*.wants/* \
  /lib/systemd/system/local-fs.target.wants/* \
  /lib/systemd/system/sockets.target.wants/*udev* \
  /lib/systemd/system/sockets.target.wants/*initctl* \
  /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
  /lib/systemd/system/systemd-update-utmp* \
  /lib/systemd/system/getty.target

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
